INHERIT: './mkbase.yml'


theme:
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.png'


site_name: 'Material for MkDocs'
site_url: 'https://nehart.ans.co.at/writing/'


site_author: 'Norbert EHART'
copyright: 'Written by <br> &ensp;Norbert EHART (norbert@ehart.net)'


nav:
  - 'Introduction': './index.md'