stages:
  - create-docker-image
  - create-release

create-docker-image:
  image: docker:latest
  stage: create-docker-image
  services:
    - docker:dind
  script: 'sh ./scripts/create-docker-image.sh'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[V]?[\d]+[\.][\d]+[\.][\d]+[-][B]?[0-9]{10}$/'

create-release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: create-release
  script: 'echo "running create-release job"'
  release:
    name: '$CI_COMMIT_TAG'
    description: 'Created with CI/CD'
    tag_name: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[V]?[\d]+[\.][\d]+[\.][\d]+[-][B]?[0-9]{10}$/'