image: python:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - cd .public
    - echo "<html><body><h1 align="center">KaTeX</h1>" > ./index.html
    - echo "<hr>" >> ./index.html
    - find -type f -exec echo "<a href='{}'>{}</a><br/>" \; >> ./index.html
    - echo "</body></html>" >> ./index.html
    - cd ..
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'