pages:
  image: 'registry.ans.co.at/templates/mmdocs/mmdocs:latest'
  stage: 'build'
  script: 'mkdocs build'
  artifacts:
    paths:
      - 'public'
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'