services:

    mkdocs:
      image: registry.ans.co.at/docker/mkdocs/mkdocs:latest
      restart: 'no'
      network_mode: 'host'
      logging:
        driver: 'journald'
      volumes:
        - './:/mnt'
        - '/etc/timezone:/etc/timezone:ro'
        - '/etc/localtime:/etc/localtime:ro'