pages:
  image: "registry.ans.co.at/templates/mmdocs/mmdocs:latest"
  stage: "build"
  script:
    - eval $(cat env.conf | sed 's/ = /=/' | sed 's/^/export /')
    - mkdocs build
  artifacts:
    paths:
      - "public"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"