INHERIT: './mkbase.yml'


theme:
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.png'


site_name: 'Lorem Ipsum'
site_url: 'https://lorem-ipsum.net'


site_author: 'John Doe'
copyright: 'Written by <br> &ensp;John DOE (john@doe.net)'


nav:
  - 'Introduction': './index.md'